export const RULE_CATEGORIES = [
  'TypeScript',
  'React',
  'Next.js',
  'Python',
  'PHP',
  'TailwindCSS',
  'Laravel',
  'C#',
  'JavaScript',
  'Game Development',
  'Expo',
  'React Native',
  'Tailwind',
  'Vite',
  'Supabase',
  'Rust',
  'Web Development',
  'Flutter',
  'API',
  'Meta-Prompt',
  'React Coding Standards',
  'React Router',
  'Redux',
  'Zustand',
  'React Query',
  'Styled Components',
  'SASS/SCSS',
  'SQL',
  'NoSQL',
  'Graph',
  'CI/CD',
  'Containerization',
  'AWS',
  'Azure',
  'Google Cloud',
  'Unit Testing',
  'Flask',
  'FastAPI',
  'Python/Spring',
  'Python/Spring Data JPA',
  'Databases',
  'MongoDB',
  'Node.js',
  'Express',
  'Vue',
  'Angular',
  'Docker',
  'Kubernetes',
  'DevOps',
  'Styling',
  'Authentication',
  'Authorization',
  'Performance',
  'Security',
  'Testing',
  'State Management',
  'PostgreSQL',
  'MySQL',
  'Firebase',
  'GraphQL',
  'REST API',
  'Mobile Development',
  'Desktop Development',
  'Web Components',
  'Microservices',
  'Serverless'
] as const;

export const DEFAULT_AUTHOR = {
  id: 'user',
  name: 'User Name',
} as const;

export const MAX_TITLE_LENGTH = 100;
export const MAX_DESCRIPTION_LENGTH = 500;
export const MAX_TAGS = 5; 